Fix/123 model deployment node selector
odahu/node-selector-webhook pull request #1
Opened 2020-06-27 15:28 UTC by vlad-tokarev

2020-06-28 21:24 UTC, karbyshevds approved these changes

2020-06-28 22:58 UTC, karbyshevds requested changes

2020-06-28 22:58 UTC, karbyshevds commented on src/main.go
> +	Short: "odahu-flow API server",
Is it correct desc?

2020-06-28 22:58 UTC, karbyshevds commented on version.info
> +#    Copyright 2019 EPAM Systems
```suggestion
#    Copyright 2020 EPAM Systems
```

2020-06-29 11:28 UTC, maxkochubey commented on README.md
> +and add configured tolerations and node selector for all pods
```suggestion
This repository contains webhook for kubernetes that assigns 
a node selector to pods in specific namespace

### How it works

Webhook monitors all pods in namespaces that 
labeled by "odahu/node-selector-webhook" (label should exist)
and adds configured tolerations and node selector for all pods 
```

2020-06-29 11:30 UTC, maxkochubey commented on scripts/Jenkinsfile
> +                        mkdir -p \$(getent passwd \$(whoami) | cut -d: -f6)/.ssh && ssh-keyscan git.epam.com >> \$(getent passwd \$(whoami) | cut -d: -f6)/.ssh/known_hosts
```suggestion
                        export GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
```

2020-06-29 11:31 UTC, maxkochubey commented on src/main.go
> +		log.Error(err, "Unable create manager")
```suggestion
		log.Error(err, "Unable to create manager")
```

2020-06-29 11:32 UTC, maxkochubey commented on scripts/Jenkinsfile
> +                        mkdir -p \$(getent passwd \$(whoami) | cut -d: -f6)/.ssh && ssh-keyscan git.epam.com >> \$(getent passwd \$(whoami) | cut -d: -f6)/.ssh/known_hosts
Let's get rid of hardcoded hostname.

2020-06-29 11:37 UTC, maxkochubey requested changes
Some suggestions below.

2020-06-30 04:19 UTC, maxkochubey approved these changes

2020-06-30 12:23 UTC, karbyshevds approved these changes

2020-06-30 14:11 UTC, merged